# Settings for the app
app:
  # HTML Title
  title: Request A Bench | CHEKPEDS
  # Header name
  name: Request A Bench in CB4
  # Meta description that will show up in Google search results
  meta_description: _(Where do you want to see benches in Hell's Kitchen?)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.76123586961813
      lng: -73.99064540863037
    zoom: 16
    minZoom: 10
    maxZoom: 22
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/doittgis.NYC_DoITT_base/{z}/{x}/{y}.png
    attribution: 'NYC basemap developed by the Department of Information Technology and Telecommunications. Based on the latest planimetric data.'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  bench_backless:
    default: bench
    focused: red
    label: _(bench)
  bench_back:
    default: bench
    focused: red
    label: _(bench)
  

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  bench:
    iconUrl: /static/css/images/markers/dot-d849e0.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/markers/marker-d849e0.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Suggest a bench!)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(suggested)
  anonymous_name: _(Someone)
  submit_button_label: _(Suggest it!)
  items:
    - prompt: _(Why put a bench here?)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(Explain why a bench is needed here...)
    - prompt: _(Location details)
      type: textarea
      name: name
      attrs:
        - key: placeholder
          value: _(Describe location, including the address)
    - prompt: _(Bench type)
      type: select
      options:
        - label: _(With Back)
          value: bench_back
        - label: _(Backless)
          value: bench_backless
      name: location_type
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30


survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(More info)
    slug: about
    url: /static/pages/overview.html
  - title: _(Siting requirements)
    slug: requirements
    url: /static/pages/requirements.html